# Set platform to iOS 16.0
platform :ios, '16.0'

target 'iosApp' do
  use_frameworks!

  # Link the Kotlin Shared Module
  pod 'composeApp', :path => '../composeApp'

  # Firebase Pods (matching those in build.gradle.kts)
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end
end
