build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LargeClass:
    active: true
    threshold: 300
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 10
  TooManyFunctions:
    active: true
    thresholdInFiles: 20

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 140
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignored|expected|serialVersionUID|tag|TAG)'

naming:
  active: true
  FunctionNaming:
    active: true
  VariableNaming:
    active: true

potential-bugs:
  active: true
  UnsafeCallOnNullableType:
    active: true

performance:
  active: true
